//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FriendsBaseASP.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FriendsBaseASP.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source=DESKTOP-VGF8T6A\MYSERVER;Initial Catalog=Portal_spolecznosciowy;Integrated Security=True;Connect Timeout=15;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrite;MultiSubnetFailover=False.
        /// </summary>
        internal static string socialMediaDatabaseConnectionString {
            get {
                return ResourceManager.GetString("socialMediaDatabaseConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE Usp_InsertUpdateDelete_Znajomy
        ///@Id_znajomego BIGINT = 0
        ///,@Imie_znajomego NVARCHAR(20) = NULL
        ///,@Nazwisko_znajomego NVARCHAR(30) = NULL
        ///,@Query INT
        ///AS
        ///BEGIN
        ///IF (@Query = 1)
        ///BEGIN
        ///INSERT INTO Znajomy(
        ///Imie_znajomego
        ///,Nazwisko_znajomego
        ///)
        ///VALUES (
        ///@Imie_znajomego
        ///,@Nazwisko_znajomego
        ///)
        ///
        ///IF (@@ROWCOUNT &gt; 0)
        ///BEGIN
        ///SELECT &apos;Insert&apos;
        ///END
        ///END
        ///
        ///IF (@Query = 2)
        ///BEGIN
        ///UPDATE Znajomy
        ///SET Imie_znajomego = @Imie_znajomego
        ///,Nazwisko_znajomego = @Nazwisko_znajomego
        ///WHERE Znajomy.I [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Usp_InsertUpdateDelete_Znajomy {
            get {
                return ResourceManager.GetString("Usp_InsertUpdateDelete_Znajomy", resourceCulture);
            }
        }
    }
}
